export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const FETCH_NEWS_ARTICLE_REQUEST = "FETCH_NEWS_ARTICLE_REQUEST";
export const FETCH_NEWS_ARTICLE_SUCCESS = "FETCH_NEWS_ARTICLE_SUCCESS";
